# Generated by Django 6.0.1 on 2026-02-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=15)),
                ('rating', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
    ]
