# Generated by Django 6.0.1 on 2026-02-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_alter_orderdetail_table_delivery_payment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delivery',
            table='Delivery',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='order',
        ),
    ]
