# Generated by Django 6.0.1 on 2026-02-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_alter_delivery_table_alter_payment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Delivery'},
        ),
    ]
