# Generated by Django 6.0.1 on 2026-02-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productcolor_product_productstatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
