# Generated by Django 6.0.1 on 2026-02-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_product_table_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100)),
                ('foodPrice', models.IntegerField()),
                ('foodDescription', models.TextField()),
                ('foodStock', models.PositiveBigIntegerField()),
                ('foodCategory', models.CharField(max_length=20, null=True)),
                ('foodStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'FoodITEM',
            },
        ),
    ]
