# Generated by Django 6.0.1 on 2026-02-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_fooditem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fooditem',
            table='fooditem',
        ),
    ]
