# Generated by Django 6.0.1 on 2026-02-06 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_fooditem_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('categoryDescription', models.TextField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100)),
                ('serviceDescription', models.TextField()),
                ('servicePrice', models.IntegerField()),
                ('serviceStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.RenameField(
            model_name='student',
            old_name='StudentName',
            new_name='studentName',
        ),
        migrations.CreateModel(
            name='studentprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentHobbies', models.CharField(choices=[('reading', 'reading'), ('travel', 'travel'), ('music', 'music')], max_length=100)),
                ('studentAddress', models.CharField(max_length=100)),
                ('studentPhone', models.CharField(max_length=10)),
                ('studentGender', models.CharField(max_length=10)),
                ('studentDOB', models.DateField()),
                ('studentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'studentprofile',
            },
        ),
    ]
