# Generated by Django 6.0.1 on 2026-02-06 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_category_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'category'},
        ),
        migrations.AddField(
            model_name='service',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.category'),
        ),
    ]
