# Generated by Django 6.0.1 on 2026-02-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_category_options_service_categoryid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
